name: Enforce Branch Merge Policy

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-pr-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Source and Target Branch
        run: |
          echo "Source: ${{ github.head_ref }}"
          echo "Target: ${{ github.base_ref }}"

          if [[ "${{ github.base_ref }}" == "develop" && "${{ github.head_ref }}" != feature/* ]]; then
            echo "❌ Only feature/* branches can merge into develop"
            exit 1
          fi

          if [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" != release/* ]]; then
            echo "❌ Only release/* branches can merge into main"
            exit 1
          fi

          echo "✅ Branch rules passed"