name: Enforce Branch Merge Policy

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-pr-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Source and Target Branch
        run: |
          echo "Source: ${{ github.head_ref }}"
          echo "Target: ${{ github.base_ref }}"

          # Check for PRs into develop
          if [[ "${{ github.base_ref }}" == "develop" ]]; then
            if [[ ! "${{ github.head_ref }}" =~ ^(feature|release|hotfix)/ ]]; then
              echo "❌ Only feature/*, release/*, and hotfix/* branches can merge into develop"
              exit 1
            fi
          fi

          # Check for PRs into master
          if [[ "${{ github.base_ref }}" == "master" ]]; then
            if [[ ! "${{ github.head_ref }}" =~ ^(release|hotfix)/ ]]; then
              echo "❌ Only release/* and hotfix/* branches can merge into master"
              exit 1
            fi
          fi

          echo "✅ Branch rules passed"