name: Tag on Release Merge

on:
  push:
    branches:
      - master

jobs:
  tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get merged branch name
        id: get_branch
        run: |
          PR_BRANCH=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls \
            -H "Accept: application/vnd.github.groot-preview+json" \
            | jq -r '.[0].head.ref')

          echo "branch_name=$PR_BRANCH" >> $GITHUB_OUTPUT

      - name: Create tag if release branch
        run: |
          BRANCH_NAME="${{ steps.get_branch.outputs.branch_name }}"
          echo "Merged branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == release/* ]]; then
            VERSION="${BRANCH_NAME#release/}"
            TAG="v$VERSION"
            echo "Creating tag: $TAG"

            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag "$TAG"
            git push origin "$TAG"
          else
            echo "Branch is not a release/* branch. Skipping tag."
          fi